name: Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Every Sunday at 4:30 am UTC.
    - cron: '30 4 * * 0'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    # Note this uses a Python package cache by default that is never
    # invalidated (without pyproject.toml, uv.lock, etc.).
    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install knit
      run: |
        curl -fsSL https://github.com/jmou/knit/releases/download/latest/knit-ubuntu-latest.tar.gz | tar xzC "$RUNNER_TEMP"
        echo "$RUNNER_TEMP/knit-ubuntu-latest" >> $GITHUB_PATH

    - name: knit
      run: |
        knit init
        knit run-plan
        knit unpack production @ --remove-prefix out/result/web/_site/ _site

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site/


  publish:
    if: github.event_name == 'push'
    needs: run
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    concurrency:
      group: "pages"

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
